# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c865f7bbdef2aecfe9d4e02c3cd1f9d5d222840b33770f40b41c49733989363f479a2288c3c566fce1b8bf7d53b740ebac37820d68ca851d222713dd110e3b91

test:
  secret_key_base: 734e0550afb135bf1c97404e26c04212886928f1ec86e5cb71e2eae1d4e75bade7a4f4b926535a9f19d3c900fd5c0d076296a3cd4a62b4a5d539f2fc458c09f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
